spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  kafka:
    in:
      telegram-bot-user-received-event:
        topic: telegram-bot-user-received-event
        consumer:
          groupId: music-event-core-group
          bootstrap-servers: localhost:29092
