spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${music-event-auth-url}
  kafka:
    in:
      telegram-bot-user-received-event:
        topic: music-event-core-topic
        consumer:
          bootstrap-servers: kafka-kafka-bootstrap.kafka-namespace.svc.cluster.local:29092
          groupId: music-event-core-group
    out:
      ticket-master-response-event:
        topic: ticket-master-response-topic
        producer:
          bootstrap-servers: kafka-kafka-bootstrap.kafka-namespace.svc.cluster.local:29092
          clientId: ticket-master-response-producer

app:
  credentials:
    ticketmaster:
      apikey: ${TICKETMASTER-APIKEY}