spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  kafka:
    in:
      telegram-bot-user-received-event:
        topic: music-event-core-topic
        consumer:
          groupId: music-event-core-group
          bootstrap-servers: localhost:29092
    out:
      ticket-master-response-event:
        topic: ticket-master-response-topic
        producer:
          bootstrap-servers: localhost:29092
          clientId: ticket-master-response-producer

app:
  urls:
    ticketmaster: https://app.ticketmaster.com/discovery/v2
  credentials:
    ticketmaster:
      apikey: GdnEbnSIzFA31WRk3pvBSC2DhGMCHgHS