apiVersion: v1
kind: ConfigMap
metadata:
  name: music-event-core-config-map
  namespace: default
data:
  music-event-auth-url: "https://music-event-bot.duckdns.org"
  telegram-bot-username: "MusicEvenHelperBot"
  ticketmaster-page-size: "3"