apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-event-core-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-test
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - music-bot-prod.duckdns.org
      secretName: music-bot-prod-tls

  rules:
    - host: music-bot-prod.duckdns.org
      http:
        paths:
          - path: /music-event-core(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: music-event-core-app-service
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-test
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - music-event-bot.duckdns.org
      secretName: music-event-bot-tls  # Reuse same cert
  rules:
    - host: music-event-bot.duckdns.org
      http:
        paths:
          - path: /kafka-ui
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 80
