# kafka-topic.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: music-event-core-topic
  namespace: kafka-namespace
  labels:
    strimzi.io/cluster: kafka  # Links to your Kafka cluster
spec:
  partitions: 2
  replicas: 1
  # Custom Kafka configuration for this topic
  config:
    retention.ms: 604800000      # 7 days in milliseconds
    segment.bytes: 1073741824     # 1GB
    cleanup.policy: delete
    compression.type: producer
    min.insync.replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ticket-master-response-topic
  namespace: kafka-namespace
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    cleanup.policy: delete
    compression.type: producer
    min.insync.replicas: 1
